--
-- PostgreSQL Unified Database Schema for Centralized CLMS
--

-- Drop tables if they exist (clean setup)
DROP TABLE IF EXISTS nudge_logs CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS change_requests CASCADE;
DROP TABLE IF EXISTS group_employees CASCADE;
DROP TABLE IF EXISTS group_courses CASCADE;
DROP TABLE IF EXISTS learning_groups CASCADE;
DROP TABLE IF EXISTS course_enrollments CASCADE;
DROP TABLE IF EXISTS course_sections CASCADE;
DROP TABLE IF EXISTS course_modules CASCADE;
DROP TABLE IF EXISTS refresh_token CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS course_progress CASCADE;
DROP TABLE IF EXISTS course_section_progress CASCADE;
DROP TABLE IF EXISTS certificates CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS course_contents CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS learning_paths CASCADE;

-- 1. Users Table
CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL DEFAULT true,
    email character varying(255) NOT NULL UNIQUE,
    full_name character varying(255),
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL CHECK (role IN ('ADMIN', 'HR', 'MANAGER', 'EMPLOYEE')),
    department character varying(255),
    designation character varying(255),
    status character varying(255) NOT NULL DEFAULT 'Compliant',
    linkedin_url character varying(1024)
);

-- 2. Courses Table
CREATE TABLE courses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL DEFAULT true,
    category character varying(255),
    description character varying(4096),
    due_date date,
    title character varying(255) NOT NULL,
    status character varying(255) NOT NULL DEFAULT 'Published',
    created_by character varying(255),
    passing_score integer NOT NULL DEFAULT 70,
    max_attempts integer NOT NULL DEFAULT 3,
    duration integer NOT NULL DEFAULT 10,
    thumbnail character varying(255),
    department character varying(255)
);

-- 3. Course Modules Table
CREATE TABLE course_modules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_order integer,
    title character varying(255) NOT NULL,
    course_id bigint REFERENCES courses(id) ON DELETE CASCADE
);

-- 4. Course Sections Table
CREATE TABLE course_sections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_type character varying(255) NOT NULL CHECK (material_type IN ('VIDEO', 'PDF', 'PPT', 'DOCUMENT')),
    material_url character varying(2048) NOT NULL,
    section_order integer,
    title character varying(255) NOT NULL,
    module_id bigint REFERENCES course_modules(id) ON DELETE CASCADE
);

-- 5. Refresh Tokens Table
CREATE TABLE refresh_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expires_at timestamp with time zone,
    token character varying(255) UNIQUE,
    user_id bigint REFERENCES users(id) ON DELETE CASCADE
);

-- 6. Course Enrollments Table
CREATE TABLE course_enrollments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint REFERENCES users(id) ON DELETE CASCADE,
    course_id bigint REFERENCES courses(id) ON DELETE CASCADE,
    employee_name character varying(255),
    course_name character varying(255),
    progress integer NOT NULL DEFAULT 0,
    status character varying(255) NOT NULL DEFAULT 'In Progress',
    quiz_score integer NOT NULL DEFAULT 0,
    enrolled_at timestamp without time zone,
    completed_at timestamp without time zone,
    due_date timestamp without time zone
);

-- 7. Learning Groups Table ( cohorts created by Managers )
CREATE TABLE learning_groups (
    id character varying(255) PRIMARY KEY,
    name character varying(255) NOT NULL,
    description character varying(2048),
    department character varying(255),
    manager_name character varying(255),
    created_date date,
    status character varying(255) NOT NULL DEFAULT 'Active'
);

-- 8. Group Courses Join Table
CREATE TABLE group_courses (
    group_id character varying(255) REFERENCES learning_groups(id) ON DELETE CASCADE,
    course_name character varying(255) NOT NULL
);

-- 9. Group Employees Join Table
CREATE TABLE group_employees (
    group_id character varying(255) REFERENCES learning_groups(id) ON DELETE CASCADE,
    employee_id character varying(255) NOT NULL
);

-- 10. Change Requests Table ( Manager review course feedback )
CREATE TABLE change_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint REFERENCES courses(id) ON DELETE CASCADE,
    title character varying(255) NOT NULL,
    feedback character varying(4096),
    priority character varying(255) NOT NULL,
    timestamp timestamp without time zone,
    resolved boolean NOT NULL DEFAULT false
);

-- 11. Audit Logs Table ( Course revision audit trail )
CREATE TABLE audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint REFERENCES courses(id) ON DELETE CASCADE,
    username character varying(255),
    action character varying(255) NOT NULL,
    status character varying(255),
    comment character varying(4096),
    timestamp timestamp without time zone
);

-- 12. Nudge Warnings Table ( Overdue reminders sent by Managers )
CREATE TABLE nudge_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id bigint REFERENCES users(id) ON DELETE CASCADE,
    employee_id bigint REFERENCES users(id) ON DELETE CASCADE,
    course_id bigint REFERENCES courses(id) ON DELETE CASCADE,
    employee_name character varying(255),
    course_name character varying(255),
    message character varying(2048),
    sent_at timestamp without time zone
);

-- 13. Course Progress Table
CREATE TABLE course_progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL,
    course_id bigint NOT NULL,
    progress_percentage integer NOT NULL,
    completed boolean NOT NULL,
    last_accessed timestamp without time zone,
    completed_at timestamp without time zone,
    attempts_used integer NOT NULL DEFAULT 0,
    is_passed boolean NOT NULL DEFAULT false,
    last_score integer
);

-- 14. Course Section Progress Table
CREATE TABLE course_section_progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL,
    course_id bigint NOT NULL,
    section_id bigint NOT NULL,
    progress integer NOT NULL,
    completed boolean NOT NULL,
    last_accessed timestamp without time zone
);

-- 15. Certificates Table
CREATE TABLE certificates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL,
    course_id bigint NOT NULL,
    certificate_path_or_url character varying(1024),
    issued_at timestamp without time zone,
    certificate_number character varying(255),
    qr_code_data character varying(255),
    verification_url character varying(255)
);

-- 16. Questions Table
CREATE TABLE questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL,
    question character varying(2048) NOT NULL,
    option_a character varying(255) NOT NULL,
    option_b character varying(255) NOT NULL,
    option_c character varying(255) NOT NULL,
    option_d character varying(255) NOT NULL,
    correct_answer character varying(255) NOT NULL
);

-- 17. Course Contents Table
CREATE TABLE course_contents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint,
    file_name character varying(255) NOT NULL,
    file_type character varying(255) NOT NULL,
    file_path character varying(1024) NOT NULL
);

-- 18. Notifications Table
CREATE TABLE notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id bigint,
    receiver_id bigint,
    message character varying(2048) NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp without time zone NOT NULL,
    type character varying(255),
    course_id bigint,
    course_title character varying(255)
);

-- 19. Learning Paths Table
CREATE TABLE learning_paths (
    id character varying(255) PRIMARY KEY,
    name character varying(255) NOT NULL,
    description character varying(2048),
    duration integer NOT NULL,
    department character varying(255)
);
